on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Render and deploy HTML document

jobs:
  build:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest, r: 'release'}
          - {os: ubuntu-20.04, r: 'release'}
          - {os: windows-latest, r: 'release'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      _R_CHECK_DONTTEST_EXAMPLES_: false
      CRAN: ${{ matrix.config.cran }}

    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-pandoc@v1
          
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1
      
      - name: Build html, word, md and pdf
        run: |-
          Rscript -e "dir.create('public')"
          Rscript -e "rmarkdown::render('UtiliserRMarkdown.Rmd', output_format = c('html_document', 'word_document', 'md_document'), output_dir = 'public')"
          Rscript -e "file.rename('public/UtiliserRMarkdown.html', 'public/index.html')"
                
      - name: Deploy HTML document to gh-pages
        if: matrix.config.os == 'ubuntu-20.04' && matrix.config.r == 'release'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: gh-pages
          publish_dir: ./public
