name: Render and deploy HTML document
'on':
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-18.04
    container: rocker/verse:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |-
          Rscript -e "install.packages(c('remotes', 'rmarkdown'), repos = 'https://muug.ca/mirror/cran/')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = 'https://muug.ca/mirror/cran/')"
      - name: Build html, word, md and pdf
        run: |-
          make html
          make word
          mv UtiliserRMarkdown.docx public
          # cp *.pdf public/
      - name: Deploy HTML document to gh-pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public





Skip to content
Pull requests
Issues
Marketplace
Explore
@KevCaz
KevCaz /
Rmarkdowndocfr

1
2

    2

Code
Issues 3
Pull requests 0
Actions
Projects 0
Wiki
Security 0
Insights

    Settings

:construction_worker: compile pdf
master @KevCaz
36c0bf5
Render and deploy HTML document on: push
Render and deploy HTML document / build
failed 14 hours ago in 50m 33s
Set up job
2s
Build peaceiris/actions-gh-pages@v2
10s
Initialize containers
1m 11s
Checkout Repository
2s
Install Dependencies
46m 32s
Build html, word, md and pdf
2m 35s
##[error]Process completed with exit code 2.
! (/github/home/.TinyTeX/texmf-dist/fonts/source/jknappen/ec/exsign.mf
!  Ok [24] [34] [35] [36] [37] [64] [191] [159])
! (/github/home/.TinyTeX/texmf-dist/fonts/source/jknappen/ec/exrlig.mf
!  Ok [25] [26] [28] [27] [29] [30] [31])
! (/github/home/.TinyTeX/texmf-dist/fonts/source/jknappen/ec/exromp.mf
!  Ok [38] [63] [190])
! (/github/home/.TinyTeX/texmf-dist/fonts/source/jknappen/ec/exrulett.mf
!  Ok [65] [66] [67] [68] [69] [70] [71] [72] [73] [74] [75] [76] [77] [78]
! [79] [80] [81] [82] [83] [84] [85] [86] [87] [88] [89] [90])
! (/github/home/.TinyTeX/texmf-dist/fonts/source/jknappen/ec/exrllett.mf
!  Ok [97] [98] [99] [100] [101] [102] [103] [104] [105] [106] [107] [108]
! [109] [110] [111] [112] [113] [114] [115] [116] [117] [118] [119] [120]
! [121] [122])
! (/github/home/.TinyTeX/texmf-dist/fonts/source/jknappen/ec/exrdigit.mf
!  Ok [48] [49] [50] [51] [52] [53] [54] [55] [56] [57])
! (/github/home/.TinyTeX/texmf-dist/fonts/source/jknappen/ec/exmligtb.mf
!  Ok) ) ) )
! Font metrics written on ectt1000.tfm.
! Output written on ectt1000.600gf (256 characters, 43832 bytes).
! Transcript written on ectt1000.log.
! mktexpk: /github/home/.TinyTeX/texmf-var/fonts/pk/ljfour/jknappen/ec/ectt1000.600pk: successfully generated.

! (/github/home/.TinyTeX/texmf-dist/fonts/source/jknappen/ec/exrlwest.mf
!  Ok [224] [225] [226] [227] [228] [229] [230] [231] [232] [233] [234] [235]
! [236] [237] [238] [239] [240] [241] [242] [243] [244] [245] [246] [247]
! [248] [249] [250] [251] [252] [253] [254] [255])
! (/github/home/.TinyTeX/texmf-dist/fonts/source/jknappen/ec/exrueast.mf
!  Ok [128] [129] [130] [131] [132] [133] [134] [135] [136] [137] [138] [139]
Deploy HTML document to gh-pages
0s
Post Checkout Repository
1s
Stop containers
0s
Complete job
0s
